import { Inter } from "next/font/google";
import "../globals.css";
import { notFound } from "next/navigation";

const inter = Inter({ subsets: ["latin"] });

// Can be imported from a shared config
const locales = ["en", "fr"];

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function LocaleLayout({ children, params: { locale } }) {
	// Validate that the incoming `locale` parameter is valid
	if (!locales.includes(locale)) notFound();

	return (
		<html lang={locale}>
			<body className={inter.className}>{children}</body>
		</html>
	);
}
